import type { Config } from '@netlify/functions';
import { getMarketplaceDatabase } from './_database';

const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0'}});
const clean=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const searchUrl=(q:string)=>`https://www.ebay.com/sch/i.html?${new URLSearchParams({_nkw:q,LH_Sold:'1',LH_Complete:'1',_sop:'13',rt:'nc'})}`;
function summarize(q:string,sales:any[],source:string,url:string){const prices=sales.map(x=>Number(x.price_cents)).filter(Number.isFinite).sort((a,b)=>a-b);const average=Math.round(prices.reduce((a,b)=>a+b,0)/prices.length);return{query:q,count:prices.length,low:prices[0],average,high:prices[prices.length-1],lastSale:Number(sales[0].price_cents),sales,source,searchUrl:url,suggestedPrice:average}}
async function ebay(q:string,url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4000);try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1','Accept':'text/html','Accept-Language':'en-US,en;q=0.9'},redirect:'follow',signal:controller.signal});if(!r.ok)return[];const html=await r.text();const blocks=html.split(/<li[^>]+class="[^"]*s-item[^"]*"[^>]*>/i).slice(1,31);const out:any[]=[];for(const b of blocks){const title=clean(b.match(/class="s-item__title"[^>]*>([\s\S]*?)<\//i)?.[1]||'').replace(/^New Listing\s*/i,'');const price=clean(b.match(/class="s-item__price"[^>]*>([\s\S]*?)<\/span>/i)?.[1]||'');const href=clean(b.match(/class="s-item__link"[^>]+href="([^"]+)"/i)?.[1]||'');const amount=Number((price.match(/\$([\d,]+(?:\.\d{1,2})?)/)||[])[1]?.replace(/,/g,''));if(title&&amount&&Number.isFinite(amount)&&!/Shop on eBay/i.test(title))out.push({title,price_cents:Math.round(amount*100),url:href||url})}return out}catch{return[]}finally{clearTimeout(timer)}}

export default async(req:Request)=>{if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const b=await req.json().catch(()=>({})) as any;const q=String(b.query||b.title||'').trim();if(q.length<3)return json({query:q,count:0,sales:[],message:'Enter at least 3 characters'});const url=searchUrl(q);const db=getMarketplaceDatabase();const like=`%${q}%`;const [external,internal]=await Promise.all([ebay(q,url),db.sql`SELECT o.item_price_cents price_cents,o.created_at,l.title,NULL::text url FROM orders o JOIN listings l ON l.id=o.listing_id WHERE o.payment_status='paid' AND l.title ILIKE ${like} ORDER BY o.created_at DESC LIMIT 20`.catch(()=>[])]);if(external.length)return json(summarize(q,external,'eBay public sold/completed listings',url));if(internal.length)return json({...summarize(q,internal,'TurboMarket verified completed sales',url),warning:'eBay prices could not be parsed automatically.'});return json({query:q,count:0,sales:[],source:'eBay sold/completed search',searchUrl:url,message:'Automatic prices were unavailable. Open the current eBay sold-results link below.'})}catch(e:any){return json({error:'Comps lookup failed',detail:e?.message||String(e)},500)}};

export const config:Config={path:'/api/comps-fast'};
